### ISSUE TITLE
Action failing to annotate on diff?

### ISSUE THREAD

**Issue by sr229** [dorny/test-reporter#130]
This action is being used a lot in [ppy/osu](https://github.com/ppy/osu), and is very critical as the annotations provides contributors and developers all the essential information without trawling through the summary immediately. However, it seems to not work apparently when opening a file [in diff view](https://github.com/ppy/osu/pull/13796/files#diff-0e0ceb285968085773cf2ca3f51a5914174dfe66358010da87a3ddfa3e8231ad). Is the action supposed to annotate this proactively without a linked PR?

**Comment by dorny** [comment]
I'm glad you find this action useful :)

Could you be more specific about what exactly seems to not work and when?
I don't understand the issue.

Anyway, there is only one place where this action checks whether it is triggered by a pull request. It is when it determines commit SHA to which the check run will be assigned - with PR you want to use SHA on a head branch, instead of SHA of temporary merge commit GitHub created. Everything else is the same.

**Comment by sr229** [comment]
> I'm glad you find this action useful :)
> 
> Could you be more specific about what exactly seems to not work and when?
> I don't understand the issue.
> 
> Anyway, there is only one place where this action checks whether it is triggered by a pull request. It is when it determines commit SHA to which the check run will be assigned - with PR you want to use SHA on a head branch, instead of SHA of temporary merge commit GitHub created. Everything else is the same.

I believe the annotations doesn't appear apparently when you're using diff view, which is exampled over there, the check and test summaries were assigning fine, only the annotations were missing for this diff view.

**Comment by dorny** [comment]
I see the annotations also in a diff view. Previously, the issue was that diff view showed only modified files, so if the annotation was assigned to a file without a modification, it was not visible. Looks like they change it now. However, the whole section is marked as "Beta". Maybe you have to manually enable these beta features until they are fully available?

Bellow is screenshot from the diff view you linked as I see it:
![image](https://user-images.githubusercontent.com/1588572/125102213-55fc7480-e0db-11eb-83c6-0ad7ab655176.png)

**Comment by sr229** [comment]
> I see the annotations also in a diff view. Previously, the issue was that diff view showed only modified files, so if the annotation was assigned to a file without a modification, it was not visible. Looks like they change it now. However, the whole section is marked as "Beta". Maybe you have to manually enable these beta features until they are fully available?
> 
> Bellow is screenshot from the diff view you linked as I see it:
> ![image](https://user-images.githubusercontent.com/1588572/125102213-55fc7480-e0db-11eb-83c6-0ad7ab655176.png)

Thanks for helping me triage the issue, I've informed the necessary party about this.

**Comment by sr229** [comment]
Thank you for helping me find out the issue @dorny, I've informed the interested party about this :D

**Comment by peppy** [comment]
Just to chime in since this issue was misreported apparently on my/our behalf: the issue we are seeing is that when this action is fired multiple times, only a single instance reports annotations (the specific instance I noticed was indeed in the new beta feature report area that you mention above).

I do not believe this is an issue with your project, but also have not done any in-depth investigation.
