### ISSUE TITLE
Issues/advice for trying to create a test report for SQL Tests

### ISSUE THREAD

**Issue by justin-newman** [dorny/test-reporter#132]
I am using RedGate tools for running SQL tests in Github and I would love to create a report for this with this tool, but it seems no matter how I run it there seems to be some kind or error.
The Redgate tools allow me to Export results to JUnit or MSTest.
So far I have tried what seems to be all of the ways and I get these errors:

RedGate test results format: JUnit
reporter: jest-junit 
Error: stackTrace.split is not a function

RedGate test results format: JUnit
reporter: java-junit 
Error: Cannot read property 'split' of undefined

RegGate test results format: MSTest
Reporter: dotnet-trx
Error: Cannot read property '0' of undefined

**Comment by dorny** [comment]
You get that errors because those parsers are specialized to work with the given framework. For example `jest-junit` works with [jest](https://jestjs.io/) test framework. It was a tradeoff to make something useful within the time I have for this project.

Could you please post here your jUnit/MSTest result files?
It will be much easier for me to fix the issue then.
