### ISSUE TITLE
Optionally skip list files step?

### ISSUE THREAD

**Issue by andybelltree** [dorny/test-reporter#210]
We have quite a large repo, so the listFiles step is using up our API rate limit. We're not really sure that it's required for us.
We were wondering if it would be possible to have an option which could be provided in order to skip this step, and produce reports without any references or links to the actual tracked files.

**Comment by dorny** [comment]
@andybelltree I assume you are processing test results previously uploaded as artifacts right? That should be the only case when files are listed using API calls. Otherwise, it's just a local git command.

There is already a `max-annotations` option. Setting it to `0` effectively disables the processing of error stack traces. In that case, listing the files is not needed and should be skipped. I'm going to fix this now.

I'm just thinking if the API rate limit is an issue, would checking out the repo work better for you? With a big repo it will probably take more time than API calls, but the API rate limit wouldn't be an issue anymore.
