### ISSUE TITLE
Include Test Result Files in the report from TRX files

### ISSUE THREAD

**Issue by icnocop** [dorny/test-reporter#58]
`<ResultFiles>` from TRX files are not included in the report.

I've attached a sample TRX file from a set of UI tests where a screenshot is taken and attached in case of an error for analysis:
```
<ResultFiles>
  <ResultFile path="fv-az28-358\error_waitingfeaturetests_waitforthescreentobeenabled_20210216_100645.html" />
  <ResultFile path="fv-az28-358\error_waitingfeaturetests_waitforthescreentobeenabled_20210216_100645.jpg" />
</ResultFiles>
```

Is it possible to include those as part of the report?

Thank you.

[TestResults.zip](https://github.com/dorny/test-reporter/files/5988086/TestResults.zip)

**Comment by dorny** [comment]
Unfortunately this is not currently possible.

Report is created as summary field in GitHub [check run](https://docs.github.com/en/rest/reference/checks#create-a-check-run).
We are limited to markdown text in report and plaintext in code annotations.

It would be possible to reference images in markdown and there is even dedicated property for image URLs on a check run. However where the images should be uploaded? I thought about artifacts API. Unfortunately any content there can be retrieved only in ZIP archive so it's not possible to reference uploaded images directly in markdown.

Originally I created this action to have a quick view on test results directly in GitHub, without downloading artifacts and evaluating test results locally. This turns out to be quite limited so one option would be to do both - create a basic markdown report directly in GitHub and then optionally create more detailed report downloadable as artifact. I will think about it. But generally I would like to keep scope of this action small. Otherwise it could explode in complexity and I don't have much spare time to work on it.

**Comment by icnocop** [comment]
Thank you for the quick and detailed explanations.

That's what I'm currently doing; in addition to calling `test-reporter`, I'm also uploading a zip with the additional test results files for further detailed analysis if/when needed.

I understand if this issue is closed.

**Comment by dorny** [comment]
I thought about it and considering my time and available solution using artifacts - I will keep this action focused only on creation of markdown report using check run API.
